project:
  type: website
  resources: 
    - vedlegg/lf/V24-2PY-loysingsforslag.pdf
    - vedlegg/lf/V24-2P-loysingsforslag.pdf

website:
  title: "Torodd F. Ottestad"
  site-url: https://lektorodd.no
  description: "Lagring for tankar, utprøvingar og løysingsforslag. Det meste er pythonrelatert i større eller mindre grad."
  navbar:
    left:
      - text: "Blogg"
        href: blogg.qmd
        icon: lightbulb
      - text: "Løysingsforslag"
        href: lf.qmd
        icon: calculator
      - text: "Mattebok"
        href: https://lektorodd.github.io/mattebok
        icon: book
      - text: "Om meg"
        href: about.qmd
        icon: person
    right:
   
      - icon: github
        href: https://github.com/lektorodd/lektorodd.no
      - icon: youtube
        href: https://www.youtube.com/channel/UCWfDrIj3Mq3Niz77HJ6cTNg
      - icon: rss-fill
        href: index.xml

format:
  html:
    theme:
      light: [journal, custom-light.scss]
      dark: [journal, custom-dark.scss]
    code-line-numbers: true
      
execute:
  freeze: auto  
comments:
  giscus:
    repo: lektorodd/lektorodd.no



